exports.up = async function(knex) {
  await knex.raw("ALTER TABLE `c_category` ADD `ALIAS` VARCHAR(128) NOT NULL AFTER `NAME`, ADD UNIQUE `ALIAS` (`ALIAS`);");
  await knex.raw("ALTER TABLE `c_user` ADD `ALIAS` VARCHAR(128) NOT NULL AFTER `ROLE`, ADD `LAST_NAME` VARCHAR(128) NOT NULL AFTER `ALIAS`, ADD `SOURCE` VARCHAR(50) NULL AFTER `LAST_NAME`, ADD `REGISTRATION_TYPE` VARCHAR(10) NOT NULL DEFAULT 'EMAIL' AFTER `SOURCE`, ADD `GOOGLE_ID` VARCHAR(40) NULL AFTER `REGISTRATION_TYPE`, ADD `FACEBOOK_ID` VARCHAR(40) NULL AFTER `GOOGLE_ID`, ADD UNIQUE `ALIAS` (`ALIAS`), ADD UNIQUE `GOOGLE_ID` (`GOOGLE_ID`), ADD UNIQUE `FACEBOOK_ID` (`FACEBOOK_ID`);");
};

exports.down = async function(knex) {
  await knex.raw("select * from c_user");
};
